name: iKRGeu
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66225
title: Just Natural Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72522600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9708fe'
    - '#39fd00'
    - '#3c00fe'
    - '#f51e1e'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
