name: iKRGeu
favicon: null
layout_spectrum: 0.682149620493874
typography_spectrum: 0.03812670963816345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6921990001574159
  lightness: 0.2970545180141926
  saturation: 0.056943537667393684
  rhythmicContrast: 0.3746239983011037
purpose: []
